# Generated by Django 2.0.13 on 2019-06-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190604_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
