# Generated by Django 2.0.13 on 2019-06-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notes_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.notes'),
            preserve_default=False,
        ),
    ]
